config/routes.rb
Rails.application.routes.draw do
  resources :homes, only: :index
  devise_for :users
  root to: "homes#index"
  resources :users, only: :show
  resources :sets, only: :index
  resources :exchange_rate_sets, only: [:new, :create, :destroy, :edit, :update]
  resources :transportation_expenses , only: [:new, :create, :destroy, :edit, :update]

  resources :manages, only: [:index] do
    collection do
      get 'm_new_item'
      get 'm_processing'
      get 'm_new_order'
      get 'm_sent_order'
    end
    member do
      get 'm_new_order_show'
      get 'm_new_order_tracking_new'
      post 'm_new_order_tracking_create'
    end
  end

  resources :infos, only: [:new, :create]

  resources :tracking_numbers, only: :update

  resources :orders, only: [:index, :edit, :update] do
    resources :tracking_numbers, only: [:index, :create]
    resources :manages, only: [:new, :create]
    collection do
      get 'processing'
      get 'tracking'
      get 'processed'
      get 'cancel'
    end
    member do
      post 'order_cancel_create'
    end
  end
  
  resources :items do
    resources :orders, only: [:new, :create]
    collection do
      get 'search'
      get 'item_hidden'
      get 'item_shiping'
    end
  end  

  resources :kaigai_orders, only: [:new, :create, :index, :show] do
    resources :kaigai_order_cancels, only: [:new, :create]
    resources :kaigai_order_pays, only: [:new, :create]
    resources :invoices, only:[:new, :create]
    collection do
      get 'kaigai_new'
      get 'kaigai_ship'
      get 'kaigai_cancel'
      get 'kaigai_invoice'
      get 'kaigai_sent'
    end
    member do
      post 'kaigai_order_over_create'
    end
  end

  resources :invoices, only:[:show] do
    member do
      post 'order_invoice_update'
    end
  end
    
end

app/models/kaigai_order.rb
class KaigaiOrder < ApplicationRecord
  belongs_to :user
  has_one :invoice
  has_one :kaigai_tracking
  has_one :kaigai_order_over
  has_one :kaigai_order_cancel
  has_one :kaigai_order_pay
  has_many :order_kaigai_orders
  has_many :orders, through: :order_kaigai_orders

  with_options presence: true do
    validates :kaigai_order_name
    validates :kaigai_order_weight
  end

  validates :kaigai_order_price, numericality: true, inclusion: { in: 1..9_999_999 }, format: { with: /\A[0-9]+\z/ }
end

app/controllers/kaigai_orders_controller.rb
class KaigaiOrdersController < ApplicationController
  before_action :set_kaigai_order, only: [:show]
  before_action :set_kaigai_orders, only: [:kaigai_new, :kaigai_ship, :kaigai_sent, :kaigai_cancel, :kaigai_invoice]
  before_action :move_to_mypage, only: [:show]

  def index
  end

  def kaigai_new
  end

  def kaigai_ship
  end

  def kaigai_sent
  end

  def kaigai_cancel
  end

  def kaigai_invoice
  end

  def kaigai_invoice_edit
  end

  def kaigai_invoice_create
  end

  def kaigai_order_over_new
    @kaigai_order_over = KaigaiOrderOver.new
  end

  def kaigai_order_over_create
    @kaigai_order_over = KaigaiOrderOver.new(kaigai_order_id: params[:id])
    if @kaigai_order_over.save
      v_orders = @kaigai_order_over.kaigai_order.orders.includes(:item)
      v_orders.each do |v_order|
        v_order.item.update(order_status_id: 1)
      end
      redirect_to user_path(current_user.id)
    else
      render :kaigai_ship
    end
  end

  def show
    @orders = @kaigai_order.orders
  end

  def create
    @new_orders = current_user.orders.where(arrival_status_id: 2)
    @kaigai_order = KaigaiOrder.new(kaigai_params)
    if @kaigai_order.valid?
      @kaigai_order.save
      v_orders = @kaigai_order.orders
      v_orders.update_all(arrival_status_id: 3)
      redirect_to kaigai_orders_path
    else
      render 'orders/processing'
    end
  end

  private

  def kaigai_params
    params.require(:kaigai_order).permit(:kaigai_order_name, :kaigai_order_price, :kaigai_order_weight,
                                         { order_ids: [] }).merge(user_id: current_user.id)
  end

  def set_kaigai_orders
    @kaigai_orders = current_user.kaigai_orders.all.order(created_at: :desc)
  end

  def set_kaigai_order
    @kaigai_order = KaigaiOrder.find(params[:id])
  end

  def move_to_mypage
    redirect_to user_path(current_user.id) if authenticate_user! && current_user.id != @kaigai_order.user_id
  end
end

app/views/kaigai_orders/index.html.erb
<%= render "shared/header" %>
<%= render "shared/user_nav_list"%>

app/views/kaigai_orders/kaigai_cancel.html.erb
<% breadcrumb :kaigai_cancel_kaigai_orders %>
<%= render "shared/header" %>
<%= render "shared/user_nav_list"%>

<div class="container">
  <div class="container">
    <table class="table table-striped">
        <thead class="bg-secondary">
          <tr>
            <th scope="col">発送依頼No.</th>
            <th scope="col">日付</th>
            <th scope="col">送料</th>
            <th scope="col">貨物重量</th>
          </tr>
        </thead>
        <tbody>
          <% @kaigai_orders.each do |order| %>
              <% if order.kaigai_order_cancel.present? %>
                <tr>
                  <td scope="row"><%= link_to order.kaigai_order_name, kaigai_order_path(order.id) %></th>
                  <td><%=l order.created_at%></td>
                  <td><%= order.kaigai_order_price %></td>
                  <td><%= order.kaigai_order_weight %></td>
                </tr>
              <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/kaigai_orders/kaigai_invoice.html.erb
<% breadcrumb :kaigai_invoice_kaigai_orders %>
<%= render "shared/header" %>
<%= render "shared/user_nav_list"%>

<div class="container">
  <div class="container">
    <table class="table table-striped">
        <thead class="bg-info">
          <tr>
            <th scope="col">発送依頼No.</th>
            <th scope="col">日付</th>
            <th scope="col">送料</th>
            <th scope="col">貨物重量</th>
            <th scope="col">支払状態</th>
            <th scope="col">インボイス</th>
          </tr>
        </thead>
        <tbody>
          <% @kaigai_orders.each do |order| %>
            <% if order.kaigai_order_pay.present? %>
              <% unless order.invoice.present? %>
              <tr>
                <td scope="row"><%= link_to order.kaigai_order_name, kaigai_order_path(order.id) %></th>
                <td><%=l order.created_at%></td>
                <td><%= order.kaigai_order_price %></td>
                <td><%= order.kaigai_order_weight %></td>
                <td>支払済</td>
                <td><%= button_to "作成", new_kaigai_order_invoice_path(order.id), {method: :get, class: "btn btn-secondary"} %></td>
              </tr>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/kaigai_orders/kaigai_new.html.erb
<% breadcrumb :kaigai_new_kaigai_orders %>
<%= render "shared/header" %>
<%= render "shared/user_nav_list"%>

<div class="container">
  <div class="container">
    <table class="table table-striped">
        <thead class="bg-primary">
          <tr>
            <th scope="col">発送依頼No.</th>
            <th scope="col">日付</th>
            <th scope="col">送料</th>
            <th scope="col">貨物重量</th>
            <th scope="col">支払い</th>
          </tr>
        </thead>
        <tbody>
          <% @kaigai_orders.each do |order| %>
            <% unless order.kaigai_order_pay.present? %>
              <% unless order.kaigai_order_cancel.present? %>
                <tr>
                  <td scope="row"><%= link_to order.kaigai_order_name, kaigai_order_path(order.id) %></th>
                  <td><%=l order.created_at%></td>
                  <td><%= order.kaigai_order_price %></td>
                  <td><%= order.kaigai_order_weight %></td>
                  <td><%= button_to "支払い", new_kaigai_order_kaigai_order_pay_path(order.id), {method: :get, class: "btn btn-secondary"} %></td>
                </tr>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/kaigai_orders/kaigai_sent.html.erb
<% breadcrumb :kaigai_sent_kaigai_orders %>
<%= render "shared/header" %>
<%= render "shared/user_nav_list"%>

<div class="container">
  <div class="container">
    <table class="table table-striped">
        <thead class="bg-success">
          <tr>
            <th scope="col">発送依頼No.</th>
            <th scope="col">日付</th>
            <th scope="col">送料</th>
            <th scope="col">貨物重量</th>
            <th scope="col">インボイス</th>
            <th scope="col">追跡番号</th>
            <th scope="col">処理済</th>
          </tr>
        </thead>
        <tbody>
          <% @kaigai_orders.each do |order| %>
            <% if order.kaigai_order_pay.present? %>
              <% if order.kaigai_order_over.present? %>
              <% if order.invoice.present? %>
              <tr>
                <td scope="row"><%= link_to order.kaigai_order_name, kaigai_order_path(order.id) %></th>
                <td><%=l order.created_at%></td>
                <td><%= order.kaigai_order_price %></td>
                <td><%= order.kaigai_order_weight %></td>
                <td><%= link_to "インボイスを表示", invoice_path(order.invoice.id) %></td>
                <td>
                  <% if order.kaigai_tracking.present? %>
                  <%= link_to order.kaigai_tracking.number, "https://trackings.post.japanpost.jp/services/srv/search/direct?searchKind=S004&locale=ja&reqCodeNo1=#{order.kaigai_tracking.number}&x=0&y=0", :target=>["_blank"] %>
                  <% else %>
                  発送中
                  <% end %>
                  </td>
                <td>
                <%= l order.kaigai_order_over.created_at %></br>
                処理済
                </td>
              </tr>
              <% end %>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/kaigai_orders/kaigai_ship.html.erb
<% breadcrumb :kaigai_ship_kaigai_orders %>
<%= render "shared/header" %>
<%= render "shared/user_nav_list"%>

<div class="container">
  <div class="container">
    <table class="table table-striped">
        <thead class="bg-warning">
          <tr>
            <th scope="col">発送依頼No.</th>
            <th scope="col">日付</th>
            <th scope="col">送料</th>
            <th scope="col">貨物重量</th>
            <th scope="col">インボイス</th>
            <th scope="col">追跡番号</th>
            <th scope="col">処理済</th>
          </tr>
        </thead>
        <tbody>
          <% @kaigai_orders.each do |order| %>
            <% if order.kaigai_order_pay.present? %>
              <% unless order.kaigai_order_over.present? %>
              <% if order.invoice.present? %>
              <tr>
                <td scope="row"><%= link_to order.kaigai_order_name, kaigai_order_path(order.id) %></th>
                <td><%=l order.created_at%></td>
                <td><%= order.kaigai_order_price %></td>
                <td><%= order.kaigai_order_weight %></td>
                <td><%= link_to "インボイスを表示", invoice_path(order.invoice.id) %></td>
                <td>
                  <% if order.kaigai_tracking.present? %>
                    <%= link_to order.kaigai_tracking.number, "https://trackings.post.japanpost.jp/services/srv/search/direct?searchKind=S004&locale=ja&reqCodeNo1=#{order.kaigai_tracking.number}&x=0&y=0", :target=>["_blank"] %>
                  <% else %>
                  発送中
                  <% end %>
                  </td>
                <td>
                <%= form_with model: @kaigai_order_over, url:kaigai_order_over_create_kaigai_order_path(order.id), local: true do |f|%>
                  <% if order.kaigai_tracking.present? %>
                    <%= f.submit "処理済に変更", class: "btn btn-warning mt-2"%>
                  <% else %>
                    処理中
                  <% end %>
                <% end %>
                </td>
              </tr>
              <% end %>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/kaigai_orders/show.html.erb
<%= render "shared/header" %>

<div class="container">
  <div class="container mb-20">
    <div class="container">
      <div class="container">
        <% unless @kaigai_order.kaigai_order_pay.present? %>
          <% if @kaigai_order.kaigai_order_cancel.present? %>
            <div class="container mt-2">
              <div class="p-3 mb-4 bg-danger text-white font-weight-bold text-center ">
                こちらの発送依頼はキャンセルされています
              </div>
            </div>
          <% else %>
            <div class="container">
              <div class="container mt-2">
                <div class="p-3 mb-2 bg-danger text-white font-weight-bold text-center ">
                  発送依頼を修正することはできません</br>
                  修正する場合、発送依頼をキャンセルしてください</br>
                  キャンセルされている発送依頼は戻すことはできません</br>
                </div>
              </div>
              <div class="container mb-4">
                <%= form_with model: @kaigai_order_cancel, url: kaigai_order_kaigai_order_cancels_path(@kaigai_order.id), local: true do |f| %>
                <%= f.text_field :arrival_status_id, type: "hidden", value: 2 %>
                <%= f.submit "オーダーをキャンセルする", class: "btn btn-dark" %>
                <% end %>
              </div>
            </div>  
          <% end %>
        <% else %>
          <div class="container mt-2">
            <div class="p-3 mb-4 bg-danger text-white font-weight-bold text-center ">
              支払い済み
              </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="container">
      <table class="table table-striped">
        <thead class="bg-primary">
          <tr>
            <th scope="col">発注日付/発注No.</th>
            <th scope="col">商品イメージ</th>
            <th scope="col">商品詳細</th>
            <th scope="col">メーカー発注番号</th>
            <th scope="col">発注個数</th>
            <th scope="col">発注金額</th>
            <th scope="col">メーカー追跡番号</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order|%>
            <tr>
              <td scope="row"><%=l order.created_at%></br>
              <%= link_to order.order_name, edit_order_path(order.id) %>
              </th>
              <td><%= image_tag order.item.image, class: "order-index-item-img" %></td>
              <td><%= link_to order.item.jp_name, item_path(order.item.id) %></td>
              <td><%= order.order_number %></td>
              <td><%= order.quantity %></td>
              <td><%= order.total_price %></td>
              <td><%= order.tracking_number.number %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>