config/routes.rb
Rails.application.routes.draw do
  resources :homes, only: :index
  devise_for :users
  root to: "homes#index"
  resources :users, only: :show
  resources :sets, only: :index
  resources :exchange_rate_sets, only: [:new, :create, :destroy, :edit, :update]
  resources :transportation_expenses , only: [:new, :create, :destroy, :edit, :update]

  resources :manages, only: [:index] do
    collection do
      get 'm_new_item'
      get 'm_processing'
      get 'm_new_order'
      get 'm_sent_order'
    end
    member do
      get 'm_new_order_show'
      get 'm_new_order_tracking_new'
      post 'm_new_order_tracking_create'
    end
  end

  resources :infos, only: [:new, :create]

  resources :tracking_numbers, only: :update

  resources :orders, only: [:index, :edit, :update] do
    resources :tracking_numbers, only: [:index, :create]
    resources :manages, only: [:new, :create]
    collection do
      get 'processing'
      get 'tracking'
      get 'processed'
      get 'cancel'
    end
    member do
      post 'order_cancel_create'
    end
  end
  
  resources :items do
    resources :orders, only: [:new, :create]
    collection do
      get 'search'
      get 'item_hidden'
      get 'item_shiping'
    end
  end  

  resources :kaigai_orders, only: [:new, :create, :index, :show] do
    resources :kaigai_order_cancels, only: [:new, :create]
    resources :kaigai_order_pays, only: [:new, :create]
    resources :invoices, only:[:new, :create]
    collection do
      get 'kaigai_new'
      get 'kaigai_ship'
      get 'kaigai_cancel'
      get 'kaigai_invoice'
      get 'kaigai_sent'
    end
    member do
      post 'kaigai_order_over_create'
    end
  end

  resources :invoices, only:[:show] do
    member do
      post 'order_invoice_update'
    end
  end
    
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, class: "alert alert-#{key}") %>
<% end %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("oiem-logo-color.png", class:"furima-icon"), root_path %>
      <% if user_signed_in? %>
      <%= form_with url: search_items_path, local: true, method: :get, class:'search-form' do |f| %>
        <%= f.text_field :keyword, placeholder: "キーワードから商品を探す", class: "input-box" %>
        <button class="search-button">
          <%= image_tag "search.png", class:"search-icon" %>
        </button>
      <% end %>
    <% end %>
  </div>
  <div class='nav'>
    <div class='lists-left'>Order Invoise Easy Management
    </div>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <% if current_user.id == 4 %>
          <li class="nav-item">
            <%= link_to "管理画面", manages_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link active" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "設定", sets_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "マイページ", user_path(current_user.id), class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link active" %>
          </li>
        <% end %>
      <% else %>
        <li class="nav-item">
          <%= link_to 'ログイン', new_user_session_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to '新規登録', new_user_registration_path, class: "nav-link active" %>
        </li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_kaigai_order_list.html.erb
<div class="container mb-3 d-flex">
<%= button_to "新規発送依頼/支払い待ち", kaigai_new_kaigai_orders_path, {method: :get, class: "btn btn-primary mr-1"} %>
<%= button_to "支払い済み/インボイス待ち", kaigai_invoice_kaigai_orders_path, {method: :get, class: "btn btn-info mr-1"} %>
<%= button_to "発送待ち", kaigai_ship_kaigai_orders_path, {method: :get, class: "btn btn-warning mr-1"} %>
<%= button_to "処理済", kaigai_sent_kaigai_orders_path, {method: :get, class: "btn btn-success mr-1"} %>
<%= button_to "キャンセル済", kaigai_cancel_kaigai_orders_path, {method: :get, class: "btn btn-dark mr-1"} %>
</div>

app/views/shared/_m_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("oiem-logo-color.png", class:"furima-icon"), manages_path %>
  </div>
  <div class='nav'>
    <div class='lists-left'>Order Invoise Easy Management
    </div>
    <ul class='lists-right'>
        <li class="nav-item">
          <%= link_to "設定", '#', class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "追跡番号登録", new_info_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link active" %>
        </li>
    </ul>
  </div>
</header>

app/views/shared/_m_order_list.html.erb
<div class="container mb-3 d-flex">
<%= button_to "新規荷物", m_new_item_manages_path, {method: :get, class: "btn btn-primary mr-1"} %>
<%= button_to "倉庫に到着済貨物", m_processing_manages_path, {method: :get, class: "btn btn-secondary mr-1"} %>
<%= button_to "新規発送依頼", m_new_order_manages_path, {method: :get, class: "btn btn-warning mr-1"} %>
<%= button_to "処理済", m_sent_order_manages_path, {method: :get, class: "btn btn-success mr-1"} %>
</div>

app/views/shared/_order_list.html.erb
<div class="container mb-3 d-flex">
<%= button_to "新規発注", orders_path, {method: :get, class: "btn btn-primary mr-1"} %>
<%= button_to "追跡番号登録発注リスト", tracking_orders_path, {method: :get, class: "btn btn-secondary mr-1"} %>
<%= button_to "倉庫に到着済発注リスト", processing_orders_path, {method: :get, class: "btn btn-warning mr-1"} %>
<%= button_to "海外倉庫発送済", sent_orders_path, {method: :get, class: "btn btn-light mr-1"} %>
<%= button_to "処理済", processed_orders_path, {method: :get, class: "btn btn-success mr-1"} %>
<%= button_to "キャンセル済", cancel_orders_path, {method: :get, class: "btn btn-dark"} %>
</div>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>OIEM利用規約</p>
  </div>
  <%= image_tag "oiem-logo-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("oiem-logo-color.png", class:"second-logo"), "/" %>
</header>

app/views/shared/_user_nav_list.html.erb
<div class="container">
<div class="container mb-1 d-flex">
<%= button_to "商品登録", new_item_path, {method: :get, class: "btn btn-primary mr-1"} %>
<%= button_to "商品一覧", items_path, {method: :get, class: "btn btn-secondary mr-1"} %>
<%= button_to "発注中商品一覧",  item_shiping_items_path, {method: :get, class: "btn btn-info mr-1"} %>
<%= button_to "非表示商品一覧", item_hidden_items_path, {method: :get, class: "btn btn-warning mr-1"} %>
</div>
<div class="container mb-1 d-flex">
<%= button_to "新規発注", orders_path, {method: :get, class: "btn btn-primary mr-1"} %>
<%= button_to "追跡番号登録発注リスト", tracking_orders_path, {method: :get, class: "btn btn-secondary mr-1"} %>
<%= button_to "倉庫に到着済発注リスト", processing_orders_path, {method: :get, class: "btn btn-warning mr-1"} %>
<%= button_to "キャンセル済", cancel_orders_path, {method: :get, class: "btn btn-dark"} %>
</div>
<div class="container mb-2 d-flex">
<%= button_to "新規発送依頼/支払い待ち", kaigai_new_kaigai_orders_path, {method: :get, class: "btn btn-primary mr-1"} %>
<%= button_to "支払い済み/インボイス待ち", kaigai_invoice_kaigai_orders_path, {method: :get, class: "btn btn-info mr-1"} %>
<%= button_to "発送待ち", kaigai_ship_kaigai_orders_path, {method: :get, class: "btn btn-warning mr-1"} %>
<%= button_to "処理済", kaigai_sent_kaigai_orders_path, {method: :get, class: "btn btn-success mr-1"} %>
<%= button_to "キャンセル済", kaigai_cancel_kaigai_orders_path, {method: :get, class: "btn btn-dark mr-1"} %>
</div>
</div>