config/routes.rb
Rails.application.routes.draw do
  resources :homes, only: :index
  devise_for :users
  root to: "homes#index"
  resources :users, only: :show
  resources :sets, only: :index
  resources :exchange_rate_sets, only: [:new, :create, :destroy, :edit, :update]
  resources :transportation_expenses , only: [:new, :create, :destroy, :edit, :update]

  resources :manages, only: [:index] do
    collection do
      get 'm_new_item'
      get 'm_processing'
      get 'm_new_order'
      get 'm_sent_order'
    end
    member do
      get 'm_new_order_show'
      get 'm_new_order_tracking_new'
      post 'm_new_order_tracking_create'
    end
  end

  resources :infos, only: [:new, :create]

  resources :tracking_numbers, only: :update

  resources :orders, only: [:index, :edit, :update] do
    resources :tracking_numbers, only: [:index, :create]
    resources :manages, only: [:new, :create]
    collection do
      get 'processing'
      get 'tracking'
      get 'processed'
      get 'cancel'
    end
    member do
      post 'order_cancel_create'
    end
  end
  
  resources :items do
    resources :orders, only: [:new, :create]
    collection do
      get 'search'
      get 'item_hidden'
      get 'item_shiping'
    end
  end  

  resources :kaigai_orders, only: [:new, :create, :index, :show] do
    resources :kaigai_order_cancels, only: [:new, :create]
    resources :kaigai_order_pays, only: [:new, :create]
    resources :invoices, only:[:new, :create]
    collection do
      get 'kaigai_new'
      get 'kaigai_ship'
      get 'kaigai_cancel'
      get 'kaigai_invoice'
      get 'kaigai_sent'
    end
    member do
      post 'kaigai_order_over_create'
    end
  end

  resources :invoices, only:[:show] do
    member do
      post 'order_invoice_update'
    end
  end
    
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :orders
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :items_status
  belongs_to :order_status

  with_options presence: true do
    with_options format: { with: /\A[a-zA-Z0-9]+\z/, message: 'は半角英文字を入力してください' } do
      validates :eng_material
      validates :eng_name
    end
    validates :jp_name
    validates :jp_material
    validates :manufacture_name
    validates :item_selection
    validates :manufacture_item_selection
    validates :manufacture_url
    validates :weight
    validates :image
    validates :items_status_id
  end

  with_options numericality: true, inclusion: { in: 0..9_999_999 }, format: { with: /\A[0-9]+\z/ } do
    validates :selling_price
    validates :purchase_price
    validates :ppurchase_price
  end

  def self.search(search)
    if search != ''
      Item.where('jp_name LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_index_item, only: [:index, :search, :item_hidden, :item_shiping]
  before_action :set_to_item, only: [:show, :edit, :update]
  before_action :move_to_index, only: [:show, :edit, :update]

  def index
  end

  def item_hidden
  end

  def item_shiping
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.valid?
      @item.save
      redirect_to user_path(current_user.id)
    else
      render :new
    end
  end

  def show
    @orders = @item.orders
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item.id)
    else
      render :edit
    end
  end

  def search
    @items = Item.search(params[:keyword])
    @user_items = @items.where(user_id: current_user.id)
    unless @user_items.present?
      flash.now[:alert] = 'キーワードに当てはまる商品がないです'
      render :index
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :eng_name, :jp_name, :jp_material, :eng_material,
                                 :manufacture_name, :item_selection, :manufacture_item_selection,
                                 :manufacture_url, :selling_price, :ppurchase_price, :purchase_price, :weight,
                                 :items_status_id, :order_status_id, :stock_quantity, :stock_standard).merge(user_id: current_user.id)
  end

  def set_to_item
    @item = Item.find(params[:id])
  end

  def set_index_item
    @display_items = Item.where(items_status_id: 1, user_id: current_user.id)
    @order_items = Item.where(items_status_id: 1, user_id: current_user.id, order_status_id: 2)
    @hiden_items = Item.where(items_status_id: 2, user_id: current_user.id)
  end

  def move_to_index
    redirect_to root_path if current_user.id != @item.user.id
  end
end

app/views/items/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('oiem-logo-color.png' , size: '185x50'), "/" %>
  </header>

  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %> 

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        【日本語】商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :jp_name, class:"items-text", id:"item-jp_name", placeholder:"日本語の商品名（必須 40文字まで)(商品検索する際に利用します)", maxlength:"40" %>
      <div class="weight-bold-text">
        【英語】商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :eng_name, class:"items-text", id:"item-eng_name", placeholder:"英語の商品名（必須 40文字まで)(インボイス作成する際に利用します)", maxlength:"40" %>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          商品表示
          <span class="indispensable">必須</span>
          <%= f.collection_select(:items_status_id, ItemsStatus.all, :id, :name, {class:"select-box", id:"item-items-status"}) %>
        </div>
        <div class="weight-bold-text">
          商品材質
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :jp_material, class:"select-box", id:"item-jp_material", placeholder:"日本語の商品材質", maxlength:"10" %>
        <%= f.text_field :eng_material, class:"select-box", id:"item-eng_material", placeholder:"英語の商品材質", maxlength:"20" %>
        <div class="weight-bold-text">
          商品重量(kg)
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :weight, class:"select-box", id:"item-weight", placeholder:"商品重量）単位kg", maxlength:"10" %>
        <div class="weight-bold-text">
          仕入メーカー名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :manufacture_name, class:"select-box", id:"item-manufacture_name", placeholder:"仕入メーカー名", maxlength:"10" %>
        <div class="weight-bold-text">
          仕入商品URL
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :manufacture_url, class:"select-box", id:"item-manufacture_url", placeholder:"仕入商品URLを貼り付けてください", maxlength:"100" %>
        <div class="weight-bold-text">
          商品項目選択肢
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :item_selection, class:"select-box", id:"item-item_selection", placeholder:"商品項目選択肢", maxlength:"10" %>
        <%= f.text_field :manufacture_item_selection, class:"select-box", id:"item-item_selection", placeholder:"メーカー商品項目選択肢", maxlength:"20" %>
        <div class="weight-bold-text">
          在庫数
            <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :stock_quantity, class:"select-box", id:"item-stock-quantity", placeholder:"在庫数を入力してください。", maxlength:"10" %>
        <div class="weight-bold-text">
          在庫通知基準個数
            <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :stock_standard, class:"select-box", id:"item-stock-standard", placeholder:"発注通知個数を入力してください", maxlength:"10" %>
      </div>
    </div>
    <%# /商品の詳細 %>


    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>商品価格</span>
        <a class="question" href="#">?</a>
      </div>
      <div>

        <div class="price-content">
          <div class="price-text">
            <span>メーカー価格</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :ppurchase_price, class:"price-input", id:"item-ppurchase_price", placeholder:"例）300" %>
        </div>

        <div class="price-content">
          <span>為替レート</span>
          <span>
            <span id='add-tax-price'></span>
          </span>
            <% if current_user.exchange_rate_sets.present? %>
              <select id="item-exchange-rate">
                <option value=0>---</option>
                <% current_user.exchange_rate_sets.each do |exchange_rate_set| %>
                  <option value=<%=exchange_rate_set.rate %>><%= exchange_rate_set.exchange_country.country %></option>
                <% end %>
              </select>
            <% else %>
              <%= link_to "レートを登録していません", new_exchange_rate_set_path %>
            <% end %>
        </div>

        <div class="price-content">
          <span>メーカー送料</span>
          <span>
            <span id='add-tax-price'></span>
          </span>
          <%= f.collection_select(:overseahoge, OverseaFeedEmsShip.all, :price, :name, {class:"select-box", id:"item-oversea-feed"}) %>
        </div>

        <div class="price-content">
          <span>販売送料</span>
          <span>
            <span id='add-tax-price'></span>
          </span>
          <%= f.collection_select(:domestichoge, current_user.transportation_expenses, :price, :name, {include_blank: "---"}, {id:"item-domestic-feed"}) %>
        </div>

        <div class="price-content">
          <div class="price-text">
            <span>仕入価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :purchase_price, class:"price-input", id:"item-purchase_price", placeholder:"自動計算されます" %>
        </div>

        <div class="price-content">
          <span>販売手数料率</span>
          <span>
            <span id='add-tax-price'></span>
          </span>
          <%= f.collection_select(:commissionhoge, Commission.all, :percent, :name, {class:"select-box", id:"item-commission"}) %>
        </div>

        <div class="price-content">
          <div class="price-text">
            <span>販売価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :selling_price, class:"price-input", id:"item-selling_price", placeholder:"例）300" %>
        </div>
        
        <div class="price-content">
          <span>販売手数料</span>
          <span>
            <span id='price-text'></span>円
        </div>

        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>

        <div class="price-content">
          <span>利益率</span>
          <span>
            <span id='profit-percent'></span>％
        </div>
        </span>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <button type="button" class="btn btn-danger">注意</button>
      <p class="sentence">
        為替レートはOIEMで提供している参考為替レートです。
      </p>
      <p class="sentence">
        メーカー送料及び販売送料は商品重量とサイズによって概算した送料であり、実際の発生する送料ではないですので、ご注意ください。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "商品を登録する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">OIEM利用規約</a></li>
    </ul>
    <%= link_to image_tag('oiem-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎OIEM,Inc.
    </p>
  </footer>
</div>

app/views/items/index.html.erb
<% breadcrumb :items %>
<%= render "shared/header" %>
<%= render "shared/user_nav_list"%>


<div class='main'>
  <div class="container">
    <div class="container">
      <table class="table table-striped">
        <thead class="bg-secondary">
          <tr>
            <th scope="col">商品イメージ</th>
            <th scope="col">商品名</th>
            <th scope="col">仕入価格</th>
            <th scope="col">在庫数</th>
            <th scope="col">発注基準値</th>
            <th scope="col">発注</th>
          </tr>
        </thead>
        <tbody>
          <% @display_items.each do |item|%>
            <tr>
              <td scope="row">
                <div class='item-img-content'>
                  <%= image_tag item.image, class: "item-img" %>
                  <div class='sold-out'>
                    <% if item.order_status_id == 2 %>
                    <span>発注中</span>
                  <% end %>
                  </div> 
                </div>
              </th>
              <td><%= link_to item.jp_name, item_path(item.id) %></td>
              <td><%= item.purchase_price %>円</td>
              <td><%= item.stock_quantity %></td>
              <td><%= item.stock_standard %></td>
              <td><%= button_to "発注する", new_item_order_path(item.id), {method: :get, class: "btn btn-secondary"} %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>  

app/views/items/item_hidden.html.erb
<% breadcrumb :item_hidden_items %>
<%= render "shared/header" %>
<%= render "shared/user_nav_list"%>

<div class='main'>
  <div class="container">
    <div class="container">
      <table class="table table-striped">
        <thead class="bg-warning">
          <tr>
            <th scope="col">商品イメージ</th>
            <th scope="col">商品名</th>
            <th scope="col">仕入価格</th>
            <th scope="col">在庫数</th>
            <th scope="col">発注基準値</th>
          </tr>
        </thead>
        <tbody>
          <% @hiden_items.each do |item|%>
            <tr>
              <td scope="row">
                <div class='item-img-content'>
                  <%= image_tag item.image, class: "item-img" %>
                  <div class='sold-out'>
                    <% if item.order_status_id == 2 %>
                    <span>発注中</span>
                  <% end %>
                  </div> 
                </div>
              </th>
              <td><%= link_to item.jp_name, item_path(item.id) %></td>
              <td><%= item.purchase_price %>円</td>
              <td><%= item.stock_quantity %></td>
              <td><%= item.stock_standard %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>  

app/views/items/item_shiping.html.erb
<% breadcrumb :item_shiping_items %>
<%= render "shared/header" %>
<%= render "shared/user_nav_list"%>

<div class='main'>
  <div class="container">
    <div class="container">
      <table class="table table-striped">
        <thead class="bg-info">
          <tr>
            <th scope="col">商品イメージ</th>
            <th scope="col">商品名</th>
            <th scope="col">仕入価格</th>
            <th scope="col">在庫数</th>
            <th scope="col">発注基準値</th>
            <th scope="col">発注</th>
          </tr>
        </thead>
        <tbody>
          <% @order_items.each do |item|%>
            <tr>
              <td scope="row">
                <div class='item-img-content'>
                  <%= image_tag item.image, class: "item-img" %>
                  <div class='sold-out'>
                    <% if item.order_status_id == 2 %>
                    <span>発注中</span>
                  <% end %>
                  </div> 
                </div>
              </th>
              <td><%= link_to item.jp_name, item_path(item.id) %></td>
              <td><%= item.purchase_price %>円</td>
              <td><%= item.stock_quantity %></td>
              <td><%= item.stock_standard %></td>
              <td><%= button_to "発注する", new_item_order_path(item.id), {method: :get, class: "btn btn-secondary"} %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>  

app/views/items/new.html.erb
<% breadcrumb :new_item %>
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('oiem-logo-color.png' , size: '185x50'), items_path %>
  </header>
  
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %> 
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        【日本語】商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :jp_name, class:"items-text", id:"item-jp_name", placeholder:"日本語の商品名（必須 40文字まで)(商品検索する際に利用します)", maxlength:"40" %>
      <div class="weight-bold-text">
        【英語】商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :eng_name, class:"items-text", id:"item-eng_name", placeholder:"英語の商品名（必須 40文字まで)(インボイス作成する際に利用します)", maxlength:"40" %>
    </div>
    <div class="items-detail">
      <div class="weight-bold-text">商品詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          商品材質
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :jp_material, class:"select-box", id:"item-jp_material", placeholder:"日本語の商品材質", maxlength:"10" %>
        <%= f.text_field :eng_material, class:"select-box", id:"item-eng_material", placeholder:"英語の商品材質", maxlength:"20" %>
        <div class="weight-bold-text">
          商品重量(kg)
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :weight, class:"select-box", id:"item-weight", placeholder:"商品重量）単位kg", maxlength:"10" %>
        <div class="weight-bold-text">
          仕入メーカー名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :manufacture_name, class:"select-box", id:"item-manufacture_name", placeholder:"仕入メーカー名", maxlength:"50" %>
        <div class="weight-bold-text">
          仕入商品URL
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :manufacture_url, class:"select-box", id:"item-manufacture_url", placeholder:"仕入商品URLを貼り付けてください", maxlength:"100" %>
        <div class="weight-bold-text">
          商品項目選択肢
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :item_selection, class:"select-box", id:"item-item_selection", placeholder:"商品項目選択肢", maxlength:"50" %>
        <%= f.text_field :manufacture_item_selection, class:"select-box", id:"item-item_selection", placeholder:"メーカー商品項目選択肢", maxlength:"50" %>
        <%= f.text_field :items_status_id, type: "hidden", value: 1 %>
        <%= f.text_field :order_status_id, type: "hidden", value: 1 %>
        <div class="weight-bold-text">
          在庫数
            <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :stock_quantity, class:"select-box", id:"item-stock-quantity", placeholder:"在庫数を入力してください。", maxlength:"10" %>
        <div class="weight-bold-text">
          在庫通知基準個数
            <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :stock_standard, class:"select-box", id:"item-stock-standard", placeholder:"発注通知個数を入力してください", maxlength:"10" %>
      </div>
    </div>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>商品価格</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>メーカー価格</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :ppurchase_price, class:"price-input", id:"item-ppurchase_price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>為替レート</span>
          <span>
            <span id='add-tax-price'></span>
          </span>
            <% if current_user.exchange_rate_sets.present? %>
              <select id="item-exchange-rate">
                <option value=0>---</option>
                <% current_user.exchange_rate_sets.each do |exchange_rate_set| %>
                  <option value=<%=exchange_rate_set.rate %>><%= exchange_rate_set.exchange_country.country %></option>
                <% end %>
              </select>
            <% else %>
              <%= link_to "レートを登録していません", new_exchange_rate_set_path %>
            <% end %>
        </div>
        <div class="price-content">
          <span>海外送料</span>
          <span>
            <span id='add-tax-price'></span>
          </span>
          <%= f.collection_select(:overseahoge, OverseaFeedEmsShip.all, :price, :name, {class:"select-box", id:"item-oversea-feed"}) %>
        </div>
        <div class="price-content">
          <span>販売送料</span>
          <span>
            <span id='add-tax-price'></span>
          </span>
          <% if current_user.transportation_expenses.present? %>
            <%= f.collection_select(:domestichoge, current_user.transportation_expenses, :price, :name, {include_blank: "---"}, {id:"item-domestic-feed"}) %>
          <% else %>
            <%= link_to "国内送料が登録されていません", new_transportation_expense_path %>
          <% end %>
        </div>
        <div class="price-content">
          <div class="price-text">
            <span>仕入価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :purchase_price, class:"price-input", id:"item-purchase_price", placeholder:"自動計算されます" %>
        </div>
        <div class="price-content">
          <span>販売手数料率</span>
          <span>
            <span id='add-tax-price'></span>
          </span>
          <%= f.collection_select(:commissionhoge, Commission.all, :percent, :name, {class:"select-box", id:"item-commission"}) %>
        </div>
        <div class="price-content">
          <div class="price-text">
            <span>販売価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :selling_price, class:"price-input", id:"item-selling_price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料</span>
          <span>
            <span id='price-text'></span>円
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        <div class="price-content">
          <span>利益率</span>
          <span>
            <span id='profit-percent'></span>％
        </div>
        </span>
      </div>
    </div>

    <div class="caution">
      <button type="button" class="btn btn-danger">注意</button>
      <p class="sentence">
        メーカー送料及び販売送料は商品重量とサイズによって概算した送料であり、実際の発生する送料ではないですので、ご注意ください。
      </p>
    </div>


    <div class="sell-btn-contents">
      <%= f.submit "商品を登録する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>

  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">OIEM利用規約</a></li>
    </ul>
    <%= link_to image_tag('oiem-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎OIEM,Inc.
    </p>
  </footer>
</div>

app/views/items/search.html.erb
<%= render "shared/header" %>

<%= form_with url: search_items_path, local: true, method: :get, class:'search-form' do |f| %>
  <%= f.text_field :keyword, placeholder: "キーワードから商品を探す", class: "input-box" %>
  <button class="search-button">
    <%= image_tag "search.png", class:"search-icon" %>
  </button>
<% end %>

<div class='main'>
  <div class='item-contents'>
    <ul class='item-lists'>
      <% @user_items.each do |item| %>
        <li class='list'>
          <%= link_to item_path(item.id) do %>
          <div class='item-img-content'>
            <%= image_tag item.image, class: "item-img" %>
          </div>
            <div class='item-info'>
              <h3 class='item-name'>
                <%= item.jp_name %>
              </h3>
              <div class='item-price'>
                <span>仕入価格：<%= item.purchase_price %>円</span>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/items/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <div class="item-img-content">
      <%= image_tag @item.image ,class:"item-box-img" %>
    </div>

    <%= link_to "商品の編集", edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
    <%= link_to "商品を発注する", new_item_order_path(@item.id) ,class:"item-red-btn"%>

    <div class="item-explain-box">
      <span><%= "商品詳細" %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">商品名【日本語】</th>
          <td class="detail-value"><%= @item.jp_name %></td>
        </tr>
        <tr>
          <th class="detail-item">商品名【英語】</th>
          <td class="detail-value"><%= @item.eng_name %></td>
        </tr>
                <tr>
          <th class="detail-item">メーカー販売価格</th>
          <td class="detail-value"><%= @item.ppurchase_price %>元(中国人民元)</td>
        </tr>
        <tr>
          <th class="detail-item">商品仕入価格</th>
          <td class="detail-value"><%= @item.purchase_price %>円</td>
        </tr>
        <tr>
          <th class="detail-item">商品販売価格</th>
          <td class="detail-value"><%= @item.selling_price %>円</td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.items_status.name %></td>
        </tr>
        <tr>
          <th class="detail-item">商品材質【日本語】</th>
          <td class="detail-value"><%= @item.jp_material %></td>
        </tr>
        <tr>
          <th class="detail-item">商品材質【英語】</th>
          <td class="detail-value"><%= @item.eng_material %></td>
        </tr>
        <tr>
          <th class="detail-item">商品在庫数</th>
          <td class="detail-value"><%= @item.stock_quantity %></td>
        </tr>
        <tr>
          <th class="detail-item">商品発注基準値</th>
          <td class="detail-value"><%= @item.stock_standard %></td>
        </tr>
        <tr>
          <th class="detail-item">仕入先名(メーカー名)</th>
          <td class="detail-value"><%= @item.manufacture_name %></td>
        </tr>
        <tr>
          <th class="detail-item">仕入先商品購入ページ</th>
          <td class="detail-value">
          <%= link_to '仕入先商品購入ページ', @item.manufacture_url, :target=>["_blank"] %>
          </td>
        </tr>
        <tr>
          <th class="detail-item">商品項目選択肢</th>
          <td class="detail-value"><%= @item.item_selection %></td>
        </tr>
        <tr>
          <th class="detail-item">メーカー商品項目選択肢</th>
          <td class="detail-value"><%= @item.manufacture_item_selection %></td>
        </tr>
        <tr>
          <th class="detail-item">商品重量</th>
          <td class="detail-value"><%= @item.weight %>kg</td>
        </tr>
      </tbody>
    </table>
  </div>
  <%# /商品の概要 %>
<div class="container">
  <div class='item-contents'>
    <h2 class='title text-muted'>発注履歴</h2>
  </div> 
  <div class="container">
    <div class="container">
      <table class="table table-striped">
        <thead class="bg-info">
          <tr>
            <th scope="col">発注日付</th>
            <th scope="col">発注数量</th>
            <th scope="col">状態</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order|%>
            <tr>
              <td><%= l order.created_at %></td>
              <td><%= order.quantity %></td>
              <td>
                <% if order.order_cancel.present? %>
                  キャンセル済
                <% elsif order.order_kaigai_orders.present? %>
                  <% order.order_kaigai_orders.each do |order_status|%>
                    <% if order_status.kaigai_order.kaigai_order_cancel.present? %>
                      キャンセルずみ
                    <% elsif order_status.kaigai_order.kaigai_order_over.present? %>
                      理済み
                    <% else %>
                      処理中
                    <% end %>
                  <% end %>
                <% else %>
                  処理中
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>  